version: "3.8"

services:
  db:
    image: mysql:8
    container_name: ecommerce-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nextdb
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: ecommerce-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://root:root@db:3306/nextdb"
      PORT: 3000
      HOST: 0.0.0.0

volumes:
  db_data:
